---
title: "Price Prediction App"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: css/styles-default.css
    #logo: img/trek_logo_2.jpeg
runtime: shiny
---

```{r setup, include=FALSE}
#setwd(here::here("app", "app_R"))

# LIBRARIES

# App
library(flexdashboard)
library(shiny)
library(shinyjs)
library(shinyWidgets)

# Core
library(tidyverse)
library(tidyquant)
library(fs)

# Visualization
library(plotly)

# Modeling
library(tidymodels)

# Artifacts & Data
bikes_tbl <- read_rds("app_data/bikes_data_clean_tbl.rds") %>% 
  mutate(product_id = str_trim(product_id, side = c("both"))) %>% 
  filter(frame_material %in% c("Carbon", "Aluminum")) %>% 
  filter(!model_name == "Supercaliber 9.9 XX1 AXS") %>% 
  filter(!model_year == 2021)


ml_model_xgboost    <- readRDS("app_artifacts/model_artifacts.rds")[[1]]
ml_model_rf         <- readRDS("app_artifacts/model_artifacts.rds")[[2]]
ml_model_glmnet     <- readRDS("app_artifacts/model_artifacts.rds")[[3]]
ml_model_mars       <- readRDS("app_artifacts/model_artifacts.rds")[[4]]

# Scripts
source("app_functions/app_functions.R")
```


Column {.sidebar}
-----------------------------------------------------------------------
```{r}
# INPUTS

# * Adding Shinyjs
useShinyjs(rmd = TRUE)

# Model Name Text Input
selectizeInput(
    inputId  = "text_bike_model", 
    label    = h4("Bike Model"),
    choices  = unique(bikes_tbl$model_name),
    selected = "Madone SLR 9 eTap Gen 7",
    multiple = FALSE
)

# * Family Picker Input
pickerInput(
    inputId  = "bike_family",
    label    = h4("Bike Family"),
    choices  = unique(bikes_tbl$family),
    selected = unique(bikes_tbl$family)[[1]]
)

br()

# * Family Year Input
pickerInput(
    inputId  = "bike_year",
    label    = h4("MFG Year"),
    choices  = unique(bikes_tbl$model_year),
    selected = unique(bikes_tbl$model_year)[[1]]
)

br()

# * Bike Category Picker Input
h4("Bike Category")
output$bike_category <- reactive ({new_bike_pred_tbl() %>% pull(category)})

textOutput(outputId = "bike_category") %>% em %>% strong()

br()

# * Frame Material Picker Input
pickerInput(
    inputId  = "frame_material",
    label    = h4("Frame Material"),
    choices  = unique(bikes_tbl$frame_material),
    selected = "Carbon"
)

br()

# * Model Selector
awesomeRadio(
   inputId = "ml_model",
   label = h4("Price Prediction Model"), 
   choices = c("XGBOOST", "RANDOM FOREST", "GLMNET", "MARS"),
   selected = "RANDOM FOREST",
   status = "primary"
)

# Break
br()
hr()
br()

# * Apply Button
actionButton(inputId = "apply", label = "Apply", icon = icon(name = "play", lib = "font-awesome"))

# * Reset Button
actionButton(inputId = "reset", label = "Reset", icon = icon("sync"))

# * Reset Observe Events
observeEvent(eventExpr = input$reset, handlerExpr = {
    
    updateSelectizeInput(
        session  = getDefaultReactiveDomain(), 
        inputId  = "text_bike_model", 
        choices  = unique(bikes_tbl$model_name),
        selected = "Madone SLR 9 eTap Gen 7"
    )
    
    updatePickerInput(
        session  = getDefaultReactiveDomain(), 
        inputId  = "bike_family", 
        selected = "Aero"
    )
    
    updatePickerInput(
        session  = getDefaultReactiveDomain(), 
        inputId  = "frame_material", 
        selected = "Carbon"
    )
    
    updateAwesomeRadio(
        session  = getDefaultReactiveDomain(),
        inputId  = "ml_model",
        selected = "RANDOM FOREST"
    )
    
    delay(ms = 300, expr = {click(id = "apply")})
})

```


Column {data-width=650}
-----------------------------------------------------------------------
```{r}

# Reactive
new_bike_pred_tbl <- eventReactive(eventExpr = input$apply, valueExpr = {

    get_new_bike_price(
        data                = bikes_tbl,
        bike_model          = input$text_bike_model,
        bike_year           = input$bike_year,
        bike_family         = input$bike_family,
        bike_frame_material = input$frame_material,
        .ml_model           = input$ml_model

    )

}, ignoreNULL = FALSE)

```

### Price Prediction vs Product Portfolio

```{r}

output$plotly_1 <- renderPlotly({
    get_price_prediction_data(bikes_tbl, new_bike_pred_tbl()) %>%
    get_price_prediction_plot()
})

plotlyOutput("plotly_1")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Price Prediction Used This Features

```{r}

renderTable({new_bike_pred_tbl() %>% get_new_bike_price_table()})

```

### Bike Image

```{r}
renderImage({

  product_id <- new_bike_pred_tbl() %>% pull(product_id)

  dir_files <- fs::dir_ls("bike_img/")

  dir_res <- dir_files %>% str_detect(product_id)

  path <- dir_files[dir_res]



    list(
      src         = path,
      contentType = "image/png",
      width       = "90%",
      alt         = product_id
    )


}, deleteFile = FALSE)

```

